# hipTensor
[components.dbg."math-libs/hipTensor/stage"]
[components.dev."math-libs/hipTensor/stage"]
[components.lib."math-libs/hipTensor/stage"]
[components.test."math-libs/hipTensor/stage"]
include = [
  # Samples
  "bin/simple_*",
  # Tests
  "bin/*_test*",
  "bin/hiptensor/CTestTestfile.cmake",
  "bin/hiptensor/bench/**",
]
