# hipTensor
[components.dbg."math-libs/hipTensor/stage"]
optional = true
[components.dev."math-libs/hipTensor/stage"]
include = [
  "include/hiptensor/*",
  "include/hiptensor/internal/*",
  "lib/cmake/hiptensor/*",
]
[components.lib."math-libs/hipTensor/stage"]
optional = true
[components.test."math-libs/hipTensor/stage"]
optional = true
include = [
  # Samples
  "bin/simple_*",
  # Tests
  "bin/*_test*",
  "bin/hiptensor/CTestTestfile.cmake",
]
