# hipTensor
[components.dbg."math-libs/hipTensor/stage"]
[components.dev."math-libs/hipTensor/stage"]
include = [
  "include/*",
  "include/**/*",
]
[components.lib."math-libs/hipTensor/stage"]
include = [
  "**/*",
]
[components.test."math-libs/hipTensor/stage"]
include = [
  "bin/*",
  "bin/**/*",
]
[components.run."math-libs/hipTensor/stage"]
