# host-blas
[components.dbg."third-party/host-blas/stage"]
[components.dev."third-party/host-blas/stage"]
[components.doc."third-party/host-blas/stage"]
[components.lib."third-party/host-blas/stage"]

# host-blas-64
[components.dbg."third-party/host-blas-64/stage"]
[components.dev."third-party/host-blas-64/stage"]
[components.doc."third-party/host-blas-64/stage"]
[components.lib."third-party/host-blas-64/stage"]

