[options]
unmatched_exclude = [
  "lib/rocm_sysdeps/share/locale/**",
  "lib/rocm_sysdeps/share/man/**",
]

# bzip2
[components.dev."third-party/sysdeps/linux/bzip2/build/stage"]
# Include the executables in the dev package since some sub-projects
# require them.
include = [
  "**/bin/*"
]
[components.lib."third-party/sysdeps/linux/bzip2/build/stage"]

# elfutils
[components.dev."third-party/sysdeps/linux/elfutils/build/stage"]
[components.lib."third-party/sysdeps/linux/elfutils/build/stage"]

# Expat
# Required by ROCgdb
[components.dev."third-party/sysdeps/linux/expat/build/stage"]
[components.doc."third-party/sysdeps/linux/expat/build/stage"]
[components.lib."third-party/sysdeps/linux/expat/build/stage"]
# Include the executable contents.
include = [
  "**/bin/*"
]

# GMP
# Required by ROCgdb.
[components.dev."third-party/sysdeps/linux/gmp/build/stage"]
[components.doc."third-party/sysdeps/linux/gmp/build/stage"]
[components.lib."third-party/sysdeps/linux/gmp/build/stage"]

# libbacktrace
# Required by amd-dbgapi library.
[components.dev."third-party/sysdeps/linux/libbacktrace/build/stage"]
[components.lib."third-party/sysdeps/linux/libbacktrace/build/stage"]

# libcap
[components.dev."third-party/sysdeps/linux/libcap/build/stage"]
[components.lib."third-party/sysdeps/linux/libcap/build/stage"]

# libdrm
[components.dev."third-party/sysdeps/linux/libdrm/build/stage"]
[components.lib."third-party/sysdeps/linux/libdrm/build/stage"]
include = [
  "**/share/**",
]

# liblzma
[components.dev."third-party/sysdeps/linux/liblzma/build/stage"]
[components.lib."third-party/sysdeps/linux/liblzma/build/stage"]

# MPFR
# Required by ROCgdb.
[components.dev."third-party/sysdeps/linux/mpfr/build/stage"]
[components.doc."third-party/sysdeps/linux/mpfr/build/stage"]
[components.lib."third-party/sysdeps/linux/mpfr/build/stage"]

# NCurses
# Required by ROCgdb
[components.dev."third-party/sysdeps/linux/ncurses/build/stage"]
[components.doc."third-party/sysdeps/linux/ncurses/build/stage"]
[components.lib."third-party/sysdeps/linux/ncurses/build/stage"]
# Include the executable contents.
include = [
  "**/bin/*"
]

# numactl
[components.dev."third-party/sysdeps/linux/numactl/build/stage"]
[components.lib."third-party/sysdeps/linux/numactl/build/stage"]

# sqlite3
[components.dev."third-party/sysdeps/linux/sqlite3/build/stage"]
[components.lib."third-party/sysdeps/linux/sqlite3/build/stage"]

# zlib
[components.dev."third-party/sysdeps/linux/zlib/build/stage"]
[components.lib."third-party/sysdeps/linux/zlib/build/stage"]

# zstd
[components.dev."third-party/sysdeps/linux/zstd/build/stage"]
[components.lib."third-party/sysdeps/linux/zstd/build/stage"]
