# amdsmi
[components.dbg."core/amdsmi/stage"]
optional = "windows"

[components.dev."core/amdsmi/stage"]
optional = "windows"

[components.doc."core/amdsmi/stage"]
optional = "windows"

[components.lib."core/amdsmi/stage"]
optional = "windows"

[components.run."core/amdsmi/stage"]
optional = "windows"
include = [
  "bin/**",
  "libexec/**",
  "share/amd_smi/**",
]

# ROCR-Runtime
[components.dbg."core/ROCR-Runtime/stage"]
[components.dev."core/ROCR-Runtime/stage"]
[components.doc."core/ROCR-Runtime/stage"]
[components.lib."core/ROCR-Runtime/stage"]
[components.run."core/ROCR-Runtime/stage"]

# rocminfo
[components.dbg."core/rocminfo/stage"]
[components.doc."core/rocminfo/stage"]
[components.run."core/rocminfo/stage"]
