name: WIP Placeholder CI Weekly

on:
    # For AMD GPU families that expect_failure, we run builds and tests from this scheduled trigger
    # schedule:
    #   - cron: "0 3 * * 0" # Runs weekly at 3 AM UTC Sundays
    workflow_dispatch:


jobs:
  call_new_weekly_ci:
    uses: ./.github/workflows/new_ci_weekly.yml
    secrets: inherit
    with:
      linux_amdgpu_families: "gfx94X-dcgpu"
